### PR TITLE
detect new patterns

### PR DESCRIPTION
**Pull request by SimonLab**
This PR target more patterns, see [issue 3](https://github.com/akitten/linkedin-canonical-url/issues/3)

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab changes look good. do you want to update the version in `package.json` ?

**Comment by SimonLab** [comment]
@nelsonic sorry I always forget the version I do this now

**Comment by nelsonic** [comment]
Sweet! :lollipop: 
Merged. :+1:

**Comment by nelsonic** [comment]
New version on NPM. :rainbow:

**Pull request merged**
